# Generated by Django 4.2.11 on 2024-04-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_baseuser_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeruser',
            name='verification_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
