# Generated by Django 4.2.11 on 2024-04-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0003_application_remove_skill_users_employer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='proile',
            new_name='profile',
        ),
    ]
