# Generated by Django 4.2.11 on 2024-04-04 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='achievement_honors',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tell_the_employer',
            field=models.TextField(default='Hi! This is something to tell my employer'),
            preserve_default=False,
        ),
    ]
