# Generated by Django 4.2.11 on 2024-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_applicantprofile_achievement_honors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='is_copy',
            field=models.BooleanField(default=False),
        ),
    ]
